# Generated by Django 4.0 on 2021-12-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='Name of image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
